name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.21'
    name: Test (Go ${{ matrix.go-version }})
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: |
          set -o pipefail
          go test ./... -json | tee ./go-test.out | go run github.com/mfridman/tparse -all
      - name: Add job summary
        if: always()
        run: |
          go run github.com/mfridman/tparse -file ./go-test.out -format markdown >> $GITHUB_STEP_SUMMARY
